tags:
  postgresql: true
  redis: true

replicaCount: 1

image:
  repository: openzaak/open-zaak
  pullPolicy: IfNotPresent
  tag: ""  # uses .Chart.AppVersion by default

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

initContainers:
  volumePerms: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  hosts:
    - open-zaak.gemeente.nl
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  size: 1Gi
  storageClassName: ''
  existingClaim: null

existingSecret: null

settings:
  allowedHosts: open-zaak.gemeente.nl
  useXForwardedHost: false

  secretKey: SOME-RANDOM-SECRET

  database:
    host: open-zaak-postgresql
    port: 5432
    username: postgres
    password: SUPER-SECRET
    name: open-zaak
    sslmode: prefer

  numProxies: 1  # use 2 if enabling ingress

  email:
    host: localhost
    port: 25
    username: ""
    password: ""
    useTLS: false

  cache:
    default: open-zaak-redis-master:6379/0
    axes: open-zaak-redis-master:6379/1

  sentry:
    dsn: ""

  jwtExpiry: 3600

  cmis:
    enabled: false
    mapperFile: ""

  isHttps: true

  debug: false

  envVars:
    OPENZAAK_SUPERUSER_EMAIL: admin@admin.org
    OPENZAAK_SUPERUSER_USERNAME: admin
    # To provide an initial password set: settings.envVars.DJANGO_SUPERUSER_PASSWORD
    OPENZAAK_DOMAIN: open-zaak.gemeente.nl
    OPENZAAK_ORGANIZATION: Gemeente
    DEMO_CONFIG_ENABLE: false
    # Notificaties -> OpenZaak auth config
    NOTIF_OPENZAAK_CLIENT_ID: open-notificaties
    NOTIF_OPENZAAK_SECRET: NOTIF_OPENZAAK_SECRET
    # OpenZaak -> Notificaties auth config
    NOTIF_API_ROOT: http://open-notificaties.default.svc.cluster.local/api/v1/
    OPENZAAK_NOTIF_CLIENT_ID: open-zaak
    OPENZAAK_NOTIF_SECRET: OPENZAAK_NOTIF_SECRET

nginx:
  image:
    repository: nginxinc/nginx-unprivileged
    pullPolicy: IfNotPresent
    tag: stable
  replicaCount: 1
  podLabels: {}
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 101
  autoscaling:
    enabled: false
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      memory: "100Mi"
      cpu: "250m"
    limits:
      cpu: "500m"
      memory: "500Mi"

#######################
# PostgreSQL subchart #
#######################

postgresql:
  primary:
    persistence:
      enabled: false
      size: 1Gi
      existingClaim: null

  global:
    postgresql:
      auth:
        database: open-zaak
        postgresPassword: SUPER-SECRET

##################
# Redis subchart #
##################

redis:
  auth:
    enabled: false

  master:
    persistence:
      enabled: false
      size: 1Gi
      existingClaim: null
