tags:
  postgresql: true
  redis: true
  rabbitmq: true

replicaCount: 1

image:
  repository: openzaak/open-notificaties
  pullPolicy: IfNotPresent
  tag: ""  # uses .Chart.AppVersion by default

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

existingSecret: null

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  hosts:
    - open-notificaties.gemeente.nl
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

worker:
  replicaCount: 1
  podLabels: {}
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

flower:
  enabled: false
  replicaCount: 1
  podLabels: {}
  service:
    type: ClusterIP
    port: 80
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}
  extraEnvVars: {}
  extraEnvVarsSecret: {}
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - open-notificaties.gemeente.nl
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

settings:
  allowedHosts: open-notificaties.gemeente.nl

  secretKey: SOME-RANDOM-SECRET

  database:
    host: open-notificaties-postgresql
    port: 5432
    username: postgres
    password: SUPER-SECRET
    name: open-notificaties
    sslmode: prefer

  numProxies: 0  # use 1 if enabling ingress

  email:
    host: localhost
    port: 25
    username: ""
    password: ""
    useTLS: false

  cache:
    default: open-notificaties-redis-master:6379/0
    axes: open-notificaties-redis-master:6379/0

  sentry:
    dsn: ""

  messageBroker:
    host: open-notificaties-rabbitmq

  celery:
    resultBackend: redis://open-notificaties-redis-master:6379/1
    # TODO: move message broker to this sub-section

  isHttps: true

  debug: false

  autoRetry:
    maxRetries: null
    backoff: null
    backoffMax: null

  flower:
    urlPrefix: ""
    basicAuth: ""

  envVars:
    OPENNOTIFICATIES_SUPERUSER_USERNAME: admin
    OPENNOTIFICATIES_SUPERUSER_EMAIL: admin@admin.org
    # To provide an initial password set: settings.envVars.DJANGO_SUPERUSER_PASSWORD
    OPENNOTIFICATIES_DOMAIN: open-notificaties.gemeente.nl
    OPENNOTIFICATIES_ORGANIZATION: Gemeente
    DEMO_CONFIG_ENABLE: false
    # Notificaties -> OpenZaak auth config
    AUTORISATIES_API_ROOT: http://open-zaak.default.svc.cluster.local/autorisaties/api/v1/
    NOTIF_OPENZAAK_CLIENT_ID: open-notificaties
    NOTIF_OPENZAAK_SECRET: NOTIF_OPENZAAK_SECRET
    # OpenZaak -> Notificaties auth config
    OPENZAAK_NOTIF_CLIENT_ID: open-zaak
    OPENZAAK_NOTIF_SECRET: OPENZAAK_NOTIF_SECRET

#######################
# PostgreSQL subchart #
#######################

postgresql:
  primary:
    persistence:
      enabled: false
      size: 1Gi
      existingClaim: null

  global:
    postgresql:
      auth:
        database: open-notificaties
        postgresPassword: SUPER-SECRET

##################
# Redis subchart #
##################

redis:
  auth:
    enabled: false

  master:
    persistence:
      enabled: false
      size: 1Gi
      existingClaim: null

#####################
# RabbitMQ subchart #
#####################

rabbitmq:
  auth:
    username: guest
    password: guest
    erlangCookie: SUPER-SECRET

  persistence:
    enabled: false
    size: 1Gi
    existingClaim: null
